#!/bin/bash

options=(
  style=round
  width=6.0
  hidpi=on
  # Rose Pine: Foam (blue) to Iris (purple), dimmed when unfocused.
  active_color='gradient(top_left=0xff9ccfd8,bottom_right=0xffc4a7e7)'
  inactive_color='gradient(top_left=0x559ccfd8,bottom_right=0x55c4a7e7)'
  blacklist='System Settings,Login Window,Notification Center,Control Center'
)

borders "${options[@]}"
